### ISSUE TITLE
Updated to 5.7.4.1

### ISSUE THREAD

**Issue by MichaelTaylor3d** [jordanlev/c5_designer_content#16]
I updated your package to be compatible with 5.7.4.1 and greater however it breaks backwards compatibility. Would you like me to do a straight pull request, alternatively we can put it on its own branch.

https://github.com/MichaelTaylor3D/c5_designer_content/

Let me know what you think? Thanks!

**Comment by jordanlev** [comment]
Hi Michael,
I **_really**_ appreciate that you took the time to do this. Unfortunately, I am not in a position right now where I have the time to review your code or merge it in (and most importantly, respond to support requests that will arise, as they always do with new versions of things). This summer I plan to devote a lot more time to Concrete5-related things, including finally diving into 5.7 and getting Designer Content updated. I will try to touch base with you again in a month or so to see where things are at. I’m really sorry about this, it’s just very unfortunate timing due to life circumstances on my part :(

   -Jordan

**Comment by MichaelTaylor3d** [comment]
Not a problem, I have some minor clean up to do on it in the meantime any way. Let me know what I can do to help when your ready.
